# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Guangyu Corey Shan's Blog"
description: "Notes on bioinformatics and data mining by G. Corey Shan"
baseurl: # the subpath of your site, e.g. "/blog"
#url: "https://gyshan.github.io"
url: "https://shanguangyu.com"
#url: "http://localhost:4000"
logo: "https://shangyblog-1256840873.cos.ap-beijing.myqcloud.com/logo.svg"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
# google_fonts:
#   - name: "Source Sans Pro"
#     weights: "400,400i,700,700i"
#   - name: "Lora"
#     weights: "400,400i,700,700i"
google_analytics: "UA-119656358-1"
disqus:
  shortname: "Guangyu"
twitter:
  username: "GuangyuShan"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Corey
  comments: true
  picture: bio-photo.jpg
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/corey-shan-6a6111a4/
      icon: fab fa-linkedin
    # - title: Instagram
    #   url: https://instagram.com/mmistakes
    #   icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/gyshan
      icon: fab fa-github-square

# Footer Links

footer_links:
  - title: LinkedIn
    url:  https://www.linkedin.com/in/corey-shan-6a6111a4/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/gyshan
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
